// src/pages/Work.tsx  (updated)
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import ProjectCard from "../assets/Card";
import AudioPlayer from "../assets/AudioPlayer.js";
import ExpandableAudio from "../assets/ExpandableAudio.js";
import "../App.css";
import React, { useEffect, useState } from "react";

type Track = {
  index: number;
  title: string;
  url: string;
  cover?: string | null;
};

const Work: React.FC = () => {
  const [tracks, setTracks] = useState<Track[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // fetch manifest (generated by the script)
    fetch("/music/manifest.json")
      .then((res) => {
        if (!res.ok) throw new Error("manifest not found");
        return res.json();
      })
      .then((data: Track[]) => {
        setTracks(data);
      })
      .catch((err) => {
        console.warn("Could not load music manifest:", err);
        setError(
          "No manifest found. Run `npm run generate-music-manifest` to create public/music/manifest.json",
        );
        setTracks([]);
      });
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div className="container" id="page">
        <div className="navigation" id="second">
          <Link to="/" className="navButton">
            Home
          </Link>
          <Link to="/about" className="navButton">
            About
          </Link>
        </div>
        <h1 id="heading">Work</h1>
        <div className="section">
          <h2>Sound Design</h2>
          <div id="spacer-large" />
          <div className="project-cards">
            <ProjectCard
              name="Redfall Trailer"
              imageUrl="/images/Redfall.webp"
              websiteUrl="/work/redfall"
            />
            <ProjectCard
              name="Paper Samurai"
              imageUrl="/images/PaperSamurai.webp"
              websiteUrl="/work/paper-samurai"
            />
            <ProjectCard
              name="Transformers"
              imageUrl="/images/Transformers.webp"
              websiteUrl="www.google.com"
            />
          </div>
          <div id="spacer-large" />
          <div id="spacer-large" />

          <h2>Music</h2>

          <div className="audio-players">
            {error && (
              <div style={{ padding: 12 }}>
                <strong>{error}</strong>
              </div>
            )}

            {tracks === null && <div>Loading tracks…</div>}

            {tracks &&
              tracks.map((t) => (
                <ExpandableAudio
                  key={t.index}
                  mname={t.title}
                  url={t.url}
                  cover={t.cover || "/images/default-cover.webp"}
                />
              ))}

            {tracks && tracks.length === 0 && !error && (
              <div style={{ padding: 12 }}>
                No tracks found in manifest. Try running{" "}
                <code>npm run generate-music-manifest</code>.
              </div>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default Work;
